services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t berndserker/meme-analyzer-api .
        - docker push berndserker/meme-analyzer-api